### ISSUE TITLE
Fix riyankanandi.css footer not showing

### ISSUE THREAD

**Issue by Sbiswas001** [Sbiswas001/Student-Portfolio#11]

**Comment by sarthakChauhan12** [comment]
Can I work on this issue? If yes, please provide some more details about the file where changes are expected.

**Comment by Sbiswas001** [comment]
In riyankanandi.html there is a line  
```html
<footer>&copy; 2024 Riyanka. All rights reserved.</footer>
``` 
which is not being shown. Fix assets/css/riyankanandi.css to fix this issue

**Comment by sarthakChauhan12** [comment]
The issue is now solved. Please check and verify. @Sbiswas001

**Comment by Sbiswas001** [comment]
Its working. Thank you!
